name: 每日早报立即推送

on:
  workflow_dispatch:  # 手动触发支持，不定时运行

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 安装 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt || true

      - name: 执行推送脚本
        env:
          ALAPI_TOKEN: ${{ secrets.ALAPI_TOKEN }}
          WPUSH_APIKEY: ${{ secrets.WPUSH_APIKEY }}
          TYPE: ${{ secrets.TYPE }}
          CHANNEL: ${{ secrets.CHANNEL }}
        run: |
          python main.py
